"%dev":
  quarkus:
    log:
      category:
        "io.drogue":
          level: DEBUG
  drogue:
    doppelgaenger:
      opcua:
        enable-anonymous: true
        self-signed-key:
          mode: ephemeral
        accept-all-client-certificates: true
